### ISSUE TITLE
why ids are longs?

### ISSUE THREAD

**Issue by podviaznikov** [michaelklishin/neocons#53]
I'm new to Neo4j but it was possible for me to save nodes with strings as ids.

However if I want to fetch node by string id I'll get error.

Because of this: https://github.com/michaelklishin/neocons/blob/master/src/clojure/clojurewerkz/neocons/rest/nodes.clj#L86

I'm not sure what is the correct behavior but it feels like current way is not consistent. It should either prohibit saving nodes with non-long ids or allow fetching nodes with non-longs.

**Comment by ricardojmendez** [comment]
Given that Neo4j accepts string ids as well, can we remove the type hint on neocons? I'll be happy to provide a pull request for 3.1.0-beta, but wanted to confirm first that having them as ints wasn't a neocons convention.

**Comment by ducky427** [comment]
@ricardojmendez AFAIK, the ID of a node and an edge is still a long. This `ID` is internal to Neo4j and you can't set that. 

A node may have a property called `id` which you can set but you can't do a direct lookup on this using the direct REST API. You need to use cypher for that using the REST API.

Hope this helps.

**Comment by ricardojmendez** [comment]
Ah yes, you are correct @ducky427, thanks!
