### ISSUE TITLE
Implement Token based user auth for Neo4j 2.2

### ISSUE THREAD

**Issue by ducky427** [michaelklishin/neocons#65]
Neo4j 2.2 is going to have token based authentication. This needs to be implemented.

See [here](http://neo4j.com/docs/snapshot/rest-api-security.html) for more details.

Latest M01 build can be found [here](http://dist.neo4j.org/neo4j-enterprise-2.2.0-M01-unix.tar.gz).

Nigel Small (@nigelsmall) has written this:

In the milestone 1, which is due soon (this week), the token-based auth will be enabled by default, to gather feedback from users, and see how it works for users and drivers.

The user does the authentication and password change in the Neo4j browser and then gets an API token generated, which is to be used with the driver. 

There is no need for a username (but there can be one provided), the API-key will be used as password. The API used is just basic auth, which most of the drivers support already.

So this will be mostly a documentation update for the drivers and, test with the milestone.

Here is the documentation for the user-level authentication APIs, and the basic auth needed for each operation with the database.

In pseudo-code:
```
authorization = 'Basic realm="Neo4j" ' + base64( ':' + token );
```
Example request

```
GET http://localhost:7474/
Accept: application/json; charset=UTF-8
Authorization: Basic realm="Neo4j" OjM3ZmQ1ZWJkOWUwY2Q3MjI3NTE5ZGE3NjY5YjIwNjEx
```

To configure / enable auth change this in neo4j-server.properties:

```
# Enable authorization

dbms.security.authorization_enabled=true 
```

Nigel Small wrote a comprehensive summary with implementation concerns.
(Thanks Nigel!!) 

Neo4j 2.2 introduces a new authentication system that requires all requests from drivers to the REST API to contain a valid API key. This will be enabled by default but can be disabled by editing the neo4j-server.properties file to set the authorization_enabled key to false:

```
dbms.security.authorization_enabled=false
```

The auth system uses two separate levels of security - a user name / password and an API key. Following installation of a fresh database, the documented way to initialise the auth system for each server setup is by entering a browser session for that server, logging in with the default user name and password of neo4j / neo4j and performing an initial password change. If successful, an API key should then be produced.

Alternatively, auth files can be copied from another (already initialised) server to a fresh install. These files are located at data/dbms/auth.db.

NOTE: Changing the default password through the browser, editing the configuration file to disable auth or cloning auth files from another server are the only documented ways to start using a freshly installed Neo4j 2.2 server.

To use the API key through REST, supply it as a password (with an empty user name) to a standard HTTP Authorization header to every request made to the server. Without this, Unauthorized responses will be returned.

I have implemented a client version of this for py2neo and the code can be found in the feature/auth2 branch:
```
https://github.com/nigelsmall/py2neo/tree/feature/auth2
```
Of particular relevance is the set_auth_token function:
```
https://github.com/nigelsmall/py2neo/blob/feature/auth2/py2neo/core.py#L135
```
This wraps the existing authenticate function which is used for alternative HTTP auth implementations such as the secured Apache proxy used by GrapheneDB. Note that the docs also require the Realm to be set.

The full set of docs can be found here:

http://neo4j.com/docs/snapshot/rest-api-security.html

**Comment by lwsamaha** [comment]
It looks like this will answer our authorization needs. The token approach fits well for us and is just what we'd hoped for. A very welcome addition to a great product.

**Comment by ducky427** [comment]
just FYI, this is work in flux. See [this discussion](https://groups.google.com/forum/#!topic/neo4j-ecosystem/rgnAE0Dyrzs)

**Comment by ducky427** [comment]
This is no longer relevant as the neo4j authorization/authentication API has changed

**Comment by ndrix** [comment]
The dbms.security.authorization_enabled key is incorrect, it should be dbms.security.auth_enabled (on my debian 7.8)

**Comment by ducky427** [comment]
@ndrix the documentation for this issue was referring to a prerelease version. As things changed materially over the release cycle, this particular issue was closed.
