### ISSUE TITLE
Blank body returned when a node label is created

### ISSUE THREAD

**Issue by mathpunk** [michaelklishin/neocons#67]
I've been working my way through the tutorial. Everything has been working as expected. And then I came to node labels (http://clojureneo4j.info/articles/populating.html#node-labels-(neo4j-2.0+) )

I tried this code: 

    (ns graphing.populating
      (:require [clojurewerkz.neocons.rest :as nr]
                    [clojurewerkz.neocons.rest.nodes :as nn]
                    [clojurewerkz.neocons.rest.labels :as nl]))

    (let [conn (nr/connect "http://localhost:7474/db/data/")
           node  (nn/create conn {:name "Clint Eastwood"})]
        (nl/add conn node "Person"))

And got 

    {:orig-content-encoding nil, :trace-redirects ["http://localhost:7474/db/data/node/42/labels"], :request-time 49, :status 204, :headers {"Server" "Jetty(9.0.5.v20130815)", "Connection" "close", "Access-Control-Allow-Origin" "*"}, :body nil}

instead of a labeled node. I fetched that 42 node, and while it existed, it did not have the new label. I can't say whether this is a problem with the function or with the documentation. 

I'm running neo4j 2.6.1, Clojure 1.6.0, and neocons 3.0.0 on Debian.

**Comment by ducky427** [comment]
Hi @mathpunk,
Do you mean running neo4j 2.1.6 instead of 2.6.1?

I checked the example you provided [Mac OS X, neo4j 2.16, neocons 3.0.0, Clojure 1.6]:

1) `clojurewerkz.neocons.rest.labels/add` doesn't return a labeled node reflecting the fact that the [API](http://neo4j.com/docs/milestone/rest-api-node-labels.html#rest-api-adding-a-label-to-a-node) also doesn't return anything.

2) After running the example you provided on an empty database, I got that the node with `{:name "Clint Eastwood"}` is labelled with `Person` in the database. The console output was similar though. 

So my end result is very different from yours.

**Comment by michaelklishin** [comment]
How does it have anything to do with CORS? I suspect you are not providing full info on your setup.

**Comment by mathpunk** [comment]
I did in fact mean 2.1.6. As for the CORS, that was merely a guess from googling about for what `"Access-Control-Allow-Origin" "*"` could possibly mean. 

I'm not sure what else to provide re: setup. I've tried executing these commands from both an ordinary lein repl and a LightTable instance, with the same results. What else might I check?

**Comment by ducky427** [comment]
@mathpunk, in your original post, you refer to "node 42". could you try it with an empty database? and could you confirm your result in the neo4j browser?

**Comment by mathpunk** [comment]
@ducky427 I emptied the database and tried a new one. The creation response was the same, and the fetch still lacked the label. However, the neo4j browser *did* appear to give the node the "Person" label.

**Comment by ducky427** [comment]
Great. Do you have a suggestion for the documentation change?

**Comment by mathpunk** [comment]
Two suggestions. First, words to the effect, "A label is not a property of a node, instead it is a ((whatever it is))"---I thought it was 'obviously' going to be a change  to the node itself. Second, I'm gathering that labels are what indices and constraints act on, somehow, and that might be made explict. "When a node is labeled, it can be placed into an index or have constraints added", or something else explaining how the three concepts interrelate.

**Comment by michaelklishin** [comment]
Thanks @mathpunk, I like the suggestions. In fact, feel free to submit a pull request for the [docs repo](https://github.com/clojurewerkz/neocons.docs) if you have a moment :)
