### ISSUE TITLE
Authentication Error on "nn/create" when auth enabled in server properties

### ISSUE THREAD

**Issue by sb3rg** [michaelklishin/neocons#73]
Forgive me if this is extremely trivial, but I'm stuck.  When authentication is enabled in the "neo4-server.properties" config file, I can't seem to be able to successfully make any "nn/create" calls as you showcase in the neocons "Create Nodes" example:

;;;;--- BEGIN SAMPLE CODE ---
(ns first_app.neocons_ex
  (:require [clojurewerkz.neocons.rest :as nr]
            [clojurewerkz.neocons.rest.nodes :as nn]))

((defn -main 
  [& args]
  ;; creates a node without properities
  (let [conn (nr/connect "http://localhost:7474/db/data/" "neo4j" "milwaukee")
        node (nn/create conn)] ;;<<< THIS LINE CAUSES ERROR (see below)
    (println node))))
;;;;--- END SAMPLE CODE ---

As you can see below in the resulting error block, despite the "conn" Connection record having ":http-auth" assigned credentials, the "nn/create" method does not carry it forward.  This keeps resulting in a:

     "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" :           
     \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"}

Error.

;;;;--- BEGIN RESULTING ERROR ---
1. Unhandled clojure.lang.ExceptionInfo
   clj-http: status 401 {:orig-content-encoding nil, :trace-redirects
   ["http://localhost:7474/db/data/node"], :request-time 22, :status
   401, :headers {"Server" "Jetty(9.2.4.v20141103)", "Connection"
   "close", "WWW-Authenticate" "None", "Content-Type"
   "application/json; charset=UTF-8", "Date" "Wed, 08 Apr 2015
   02:09:40 GMT"}, :body "{\n \"errors\" : [ {\n \"message\" : \"No
   authorization header supplied.\",\n \"code\" :
   \"Neo.ClientError.Security.AuthorizationFailed\"\n } ]\n}"}
   {:object
    {:orig-content-encoding nil,
     :trace-redirects ["http://localhost:7474/db/data/node"],
     :request-time 22,
     :status 401,
     :headers
     {"Server" "Jetty(9.2.4.v20141103)",
      "Connection" "close",
      "WWW-Authenticate" "None",
      "Content-Type" "application/json; charset=UTF-8",
      "Date" "Wed, 08 Apr 2015 02:09:40 GMT"},
     :body
     "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"},
    :environment
    {client
     #<client$wrap_output_coercion$fn__9332 clj_http.client$wrap_output_coercion$fn__9332@29e51476>,
     req
     {:headers
      {"accept" "application/json", "content-type" "application/json"},
      :throw-entire-message? true,
      :url "http://localhost:7474/db/data/node",
      :content-type :json,
      :body "{}",
      :request-method :post,
      "neo4j" "milwaukee"},
     map__9218
     {:orig-content-encoding nil,
      :trace-redirects ["http://localhost:7474/db/data/node"],
      :request-time 22,
      :status 401,
      :headers
      {"Server" "Jetty(9.2.4.v20141103)",
       "Connection" "close",
       "WWW-Authenticate" "None",
       "Content-Type" "application/json; charset=UTF-8",
       "Date" "Wed, 08 Apr 2015 02:09:40 GMT"},
      :body
      "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"},
     resp
     {:orig-content-encoding nil,
      :trace-redirects ["http://localhost:7474/db/data/node"],
      :request-time 22,
      :status 401,
      :headers
      {"Server" "Jetty(9.2.4.v20141103)",
       "Connection" "close",
       "WWW-Authenticate" "None",
       "Content-Type" "application/json; charset=UTF-8",
       "Date" "Wed, 08 Apr 2015 02:09:40 GMT"},
      :body
      "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"},
     status 401}}

                    client.clj:  155  clj-http.client/wrap-exceptions/fn
                    client.clj:  489  clj-http.client/wrap-accept/fn
                    client.clj:  504  clj-http.client/wrap-accept-encoding/fn
                    client.clj:  479  clj-http.client/wrap-content-type/fn
                    client.clj:  595  clj-http.client/wrap-form-params/fn
                    client.clj:  618  clj-http.client/wrap-nested-params/fn
                    client.clj:  578  clj-http.client/wrap-method/fn
                   cookies.clj:  121  clj-http.cookies/wrap-cookies/fn
                     links.clj:   50  clj-http.links/wrap-links/fn
                    client.clj:  638  clj-http.client/wrap-unknown-host/fn
                    client.clj:  753  clj-http.client/post
                   RestFn.java:  423  clojure.lang.RestFn/invoke
                      rest.clj:   60  clojurewerkz.neocons.rest/POST
                   RestFn.java:  464  clojure.lang.RestFn/invoke
                     nodes.clj:   45  clojurewerkz.neocons.rest.nodes/create
                     nodes.clj:   43  clojurewerkz.neocons.rest.nodes/create
                neocons_ex.clj:   16  first-app.neocons-ex/-main
                   RestFn.java:  397  clojure.lang.RestFn/invoke
                          REPL:    1  first-app.neocons-ex/eval11279
                 Compiler.java: 6703  clojure.lang.Compiler/eval
                 Compiler.java: 6666  clojure.lang.Compiler/eval
                      core.clj: 2927  clojure.core/eval
                      main.clj:  239  clojure.main/repl/read-eval-print/fn
                      main.clj:  239  clojure.main/repl/read-eval-print
                      main.clj:  257  clojure.main/repl/fn
                      main.clj:  257  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   67  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  624  clojure.core/apply
                      core.clj: 1862  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   51  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  183  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  152  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1145  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  615  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

;;; --- END RESULTING ERROR ---

Am I missing something or is this a known issue?

I would greatly appreciate any help you could offer.

**Comment by ducky427** [comment]
@sb3rg, I tried the exact code provided [with my password ofcourse], and it works for me.

Questions:
1) What version of Neocons are you using? I tested with `3.1.0-beta3`.
2) Can you login to the neo4j browser with your auth details?

**Comment by sb3rg** [comment]
I'm using version 3.0.0 and I can login to the localhost:7474/browser with the auth details.

I'm seeing in the error list under "headers":

:headers
{"Server" "Jetty(9.2.4.v20141103)",
"Connection" "close",
"WWW-Authenticate" "None",  <<<<<<-------------- maybe this has something to do with it?
"Content-Type" "application/json; charset=UTF-8",
"Date" "Wed, 08 Apr 2015 02:09:40 GMT"},

I'm not sure how to fix, that though or if that's even the right thing.

**Comment by sb3rg** [comment]
And thank you for getting back to me so quickly!

**Comment by ducky427** [comment]
Could you try `3.1.0-beta3`?

**Comment by sb3rg** [comment]
Sure! I'll give it a whirl this afternoon and get back to you.  Thanks again!

**Comment by sb3rg** [comment]
Ok! I tried it with 3.1.0-beta3 and it works.  Still not sure why it wasn't working with 3.0.0, but hey.... it works!  Your help was much appreciated!

**Comment by pandeiro** [comment]
Hi @ducky427 @sb3rg ,

I'm still having this issue, with `3.1.0-beta3` and neo4j `2.2.0`, although it happens on the first call to `clojurewerkz.neocons.rest/connect`. A login and password has been set in the neo4j instance (required as of 2.2.0) and those credentials are present in the environment as `NEO4J_LOGIN` and `NEO4J_PASSWORD`.

Is there a way I can debug this? (Would it be better to open a new issue? I thought it must be related to this, but maybe not?)

**Comment by ducky427** [comment]
Hi @pandeiro,
You don't need to set the two environment variables. Could you try testing with using this signature of connect: `(connect uri login password)`. See [API docs](http://reference.clojureneo4j.info/clojurewerkz.neocons.rest.html#var-connect) for details.

**Comment by pandeiro** [comment]
@ducky427 Thanks a lot for pointing me to the relevant, updated API docs and apologies for the late response -- that did work great.

Just FYI, the documentation site doesn't include that info:
http://clojureneo4j.info/articles/getting_started.html#connecting-to-neo4j
