### ISSUE TITLE
Fix warning with `clojure.core.update` being replaced

### ISSUE THREAD

**Issue by grabbou** [michaelklishin/neocons#75]
Clojure 1.7 RC1
Neocons 3.1.0-beta3 (mainly because of the WWW-Authenticate issue)

http://www.reddit.com/r/Clojure/comments/37vl57/warning_update_already_refers_to/
https://github.com/Prismatic/plumbing/issues/76

Sample solution:
https://github.com/jkk/honeysql/pull/41/files

WDYT? The warning is harmless currently, but I'd like to keep my console warning free where possible! The update is relatively small and should be all about explicitly referencing `neocons` update. Can submit a PR with above if that's something you'd like to see implemented.

**Comment by michaelklishin** [comment]
@grabbou feel free to submit a PR that adds an exclude.

**Comment by ducky427** [comment]
FWIW, I think @andrew-nguyen already fixed that in 05c1fd94cc495e0f3fb742fae64d479252ef70f7. We just need to do a release of it.

**Comment by grabbou** [comment]
Ha, true!
