### ISSUE TITLE
Return information from MERGE Cypher Statements

### ISSUE THREAD

**Issue by joshuacano** [michaelklishin/neocons#76]
It seems that when you run a MERGE statement against a transaction endpoint or run a MERGE against query, any results of the statement are not Propagated back to the client. Would be helpful for reporting on how many items of the graph were impacted. (How many properties created, Nodes/Relationships created) Perhaps I will try and add this functionality myself as a pull request.

**Comment by michaelklishin** [comment]
@joshuacano would you mind providing a code example, what is returned and what you expect to be returned?

**Comment by joshuacano** [comment]
Its actually a bug further up in the rest api provided from Neo4j. If you post to the REST or Legacy Cypher endpoint a simple merge statement (I.e. { "statements" : [{ "statement" : "MATCH (w:Work) with w limit 10 set w.test = 0 " }] } The endpoint will provide no response as to what it has done. If you post this same simple statement to the Browser, you will get a meaningful response. (In this case. Set 10 properties, statement executed in 300 ms) Sorry for posting this here! This Is a problem in the cypher endpoint and I will post to neo4j forums. Love this library thanks!
