### ISSUE TITLE
Creation of node with type

### ISSUE THREAD

**Issue by gdulus** [michaelklishin/neocons#77]
Hey 

First of all, thank you for this great library. I have a noobie but i couldn't find an answer in documentation. 
Is there any way to create node with the type. In Cypher i can execute something like 

```
CREATE (n:Person { name : 'Andres', title : 'Developer' })
```
i can't find an option to do that in Neocons:

```
 (nn/create conn {:url "http://clojurewerkz.org"})
```

**Comment by ducky427** [comment]
Hi @gdulus,
Its not currently possible to create a node AND add a label to the node at the same time without resorting to Cypher. Its the way Neo4j REST API has been designed.

The two choices you have:

1. Create a node and then add a label to it. Example [here](http://clojureneo4j.info/articles/populating.html#node-labels-(neo4j-2.0+)).

1. Use Cypher to execute `CREATE (n:Person { name : 'Andres', title : 'Developer' })`. Neocons cypher guide is [here](http://clojureneo4j.info/articles/cypher.html)
