### ISSUE TITLE
Add ability to use either `batch` or `transaction` for regular methods (such as nn/get, lbl/get-all-nodes, etc).

### ISSUE THREAD

**Issue by johanatan** [michaelklishin/neocons#80]
Alternatively, one could allow the existing [regular] methods to return values suitable as input to the existing `batch` or `transaction` methods: i.e., either a) Cypher or b) the REST params and request type.

**Comment by michaelklishin** [comment]
We will no modify existing functions to do two different things. A new set of namespaces can be added but I'm not too excited about maintaining two APIs.

@ducky427 WDYT?

**Comment by johanatan** [comment]
My suggestion of course was not to modify existing functions to do two separate things but rather to add a new set of functions that returns inputs suitable for 'batch' or 'transaction' and modify the existing functions to also use that new set of functions to do most of their work. Pretty standard legacy system maintenance technique.

**Comment by johanatan** [comment]
My suggestion of course was not to modify existing functions to do two separate things but rather to add a new set of functions that returns inputs suitable for 'batch' or 'transaction' and modify the existing functions (or preferably generate them from the new set) to also use that new set of functions to do most of their work. It's a pretty standard legacy system maintenance technique.

It's really a pity the system wasn't designed for this from the beginning however as it would have been much less work than it is now.

**Comment by johanatan** [comment]
My suggestion of course was not to modify existing functions to do two separate things but rather to modify the existing set of functions to return inputs suitable for 'batch' or 'transaction' and add a new set  of functions (or preferably generate them from the old set) to use the existing set of functions to do most/all? of their work. It's a pretty standard legacy system maintenance technique.

It's really a pity the system wasn't designed for this from the beginning however as it would have been much less work than it is now.

**Comment by johanatan** [comment]
My suggestion of course was not to modify existing functions to do two separate things but rather to modify the existing set of functions to return inputs suitable for 'batch' or 'transaction' and add a new set  of functions (or preferably generate them from the old set) to use the existing set of functions to do most/all? of their work (of course maintaining the same contracts in this new set as it currently expected from the existing set). It's a pretty standard legacy system maintenance technique.

It's really a pity the system wasn't designed for this from the beginning however as it would have been much less work than it is now.

**Comment by ducky427** [comment]
Given that in Neo4j 3.0, Neo4j team are talking about introducing [a new Cypher based binary protocol](https://github.com/neo4j/neo4j-java-driver) for communication with the database, I see over time people switching over to that from this current REST API.

We can talk about adding helper functions for that future API. But I am also not in favour of changing the way the current APIs work.

**Comment by michaelklishin** [comment]
@ducky427 it's more about having 2 APIs. For example, Elastisch has been maintaining 2 nearly identical APIs for binary and REST clients for years. It was worth it because native client offers 5 times the throughput. I can see Neocons doing the same going forward.

However, having an API for creating bulk operation items sounds not worth the effort for me.

**Comment by johanatan** [comment]
You guys do realize that the current REST API you have here is virtually useless for anyone who cares about data integrity/consistency? For example, let's suppose I want to create a node and assign it a label as an atomic operation (which is pretty standard database requirement). I am left either to do:

a) write it all in Cypher and use `transaction` support.
b) hand-craft some uri and param arguments to `batch`.
c) use the nice functions which abstract away the REST calls and do my own detection of and rollback of any operations which fail in application logic.

Your implementations of a & b are like 25 lines of this entire project so I think it is fair to say that any "value add" you might have to offer would fall under the c) option yet this one handles no atomicity and forces it all upon the application developer (virtually making the library useless).

**Comment by michaelklishin** [comment]
@johanatan that's how REST works everywhere and it happens to be the primary transport for Neo4J. Back when Neocons was started, even batches may or may not have been around.

If you find Neocons virtually useless, feel free to develop your own client.

**Comment by michaelklishin** [comment]
In ~ 4 years of Neocons history, this has been requested twice at most. Perhaps our users don't give a damn about data integrity. Or what the library offers is not too bad.

I should point out that whenever someone with strong opinions, such as @johanatan, is pushing for a feature, it's worth asking ourselves: will that person be around to maintain it in the future? From my experience with many open source projects, in Clojure or not, in 99.99% of the cases the answer is "no".

So if we end up maintaining 4 APIs (REST + binary x regular + batch), it will all be on us. I am not convinced that the suggested batch/transaction API is worth doubling the maintenance effort on my and @ducky427's end. So we are not going to pursue this.

**Comment by michaelklishin** [comment]
Unlocking as promised in #81. @ducky427 if you feel this is worth resolving, even if it doubles e.g. the number of test cases and docs we'll have to maintain, I trust your judgement.

**Comment by ducky427** [comment]
I think the biggest concern for me is not breaking the API and any changes proposed are backward compatible.
