### ISSUE TITLE
Adapt tests to use authentication

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/neocons#82]
Neo4J server 2.2 enables authentication by default. We should adjust our test suite to use it. A well-known set of credentials set up via a shell script is OK.

@ducky427 thoughts?

**Comment by ducky427** [comment]
We should be able to adjust our `before_install` script to change the default password before testing. 

Alternatively, I am in two minds of using their [TestServerBuilder](http://neo4j.com/docs/stable/server-unmanaged-extensions-testing.html) API which lets us start and stop the server from within our test suite. I doubt it has support for auth though. So thats a big downside of it.

**Comment by ducky427** [comment]
@michaelklishin, is it ok to write that script using python and [requests](https://github.com/kennethreitz/requests). We need to basically make a call to the db with default login and password, get an auth token and make another call to set the new password.

**Comment by michaelklishin** [comment]
@ducky427 I don't mind Python but if it's just an HTTP request, can't we just use `curl`?

**Comment by ducky427** [comment]
ok. let me try.

**Comment by ducky427** [comment]
@michaelklishin, looks like the work is already done. I updated the build script to download Neo4j 2.2.5 and all the tests [pass](https://travis-ci.org/michaelklishin/neocons/builds/81579381). Auth is enabled for the tests.

**Comment by michaelklishin** [comment]
@ducky427 sweet, thank you! Feel free to close this.

**Comment by ducky427** [comment]
great. I'll create a PR to update the Neo4j version tested.
