### ISSUE TITLE
Result set streaming support

### ISSUE THREAD

**Issue by tuddman** [michaelklishin/neocons#86]
Has streaming responses been considered as an option for inclusion to `Connection`?

from http://neo4j.com/docs/stable/rest-api-streaming.html
looks to be as simple as adding the header:

```
X-Stream: true
```

**Comment by michaelklishin** [comment]
I have some doubts it is as simple as claimed. Such client API either has to look differently (e.g. use callbacks) or accumulate the entire result set before returning it, largely defying the whole purpose of streaming, or return a very different value that is computed incrementally.

So likely every listing API function will have to have a streaming version.

**Comment by ducky427** [comment]
I agree with @michaelklishin's comments. Implementing streaming support is a non-trivial exercise.

**Comment by tuddman** [comment]
closing this ... in favor of focusing on implementing neo4j's preferred BOLT protocol which, with an 'always on' connection, is said to be much more performant than batched REST queries.
