### ISSUE TITLE
Support Neo4j's new Bolt Protocol

### ISSUE THREAD

**Issue by ducky427** [michaelklishin/neocons#88]
I've start work on this [here](https://github.com/ducky427/clj-neo-bolt).

The API is very minimal and simple.

Should I put the work in `clojurewerkz.neocons.bolt` namespace?

**Comment by michaelklishin** [comment]
@ducky427 sounds good. Feel free to push into this repo on a branch.

So it will be a separate binary client in the same library, correct? We've had this in Elastisch for 4 or so years now with as close APIs as possible between the two clients.

**Comment by ducky427** [comment]
@michaelklishin, I agree. I'm trying to model the atleast the function names and arguments very similarly. But of course there will be some differences.

**Comment by tuddman** [comment]
The REST query statement supported passing a full clojure map as a parameter: provided it was at least stringify-keyed to something like `"data"`   e.g.:

```
(ntx/statement "(CREATE n {data} RETURN n") { "data" {:name "Arthur" :rank "King"}})
```

...which made it much easier to create/read/update/delete nodes & relationships without having to know - and declare in the query string - the specific properties to set ahead of time.

it would be really nice for the bolt driver to support the same, without having to know & specify the named fields:

so this most basic query+param works, because `name` is explicitly declared as a property in the constructed query string
```
(neobolt/query tx "CREATE (n {name: {name}}) RETURN n" {"name" "Arthur"})
```

but anything more interesting doesn't (yet)
```
(neobolt/query tx "CREATE (n {data}) RETURN n" {"data" {:name "Arthur" :additonal "passed-in-detail"}})
```

**Comment by ducky427** [comment]
@tuddman, it's because the new code doesn't do any type coercion. It passes the parameters to the underlying java library transparently.

So need to investigate, how we can handle keywords while sending data.

Further, the following code fails:

```clojure
(neobolt/query tx "CREATE (n {data}) RETURN n" {"data" {"name" "Arthur" "additional" "passed-in-detail"}})
```

with the following error:
```
org.neo4j.driver.v1.exceptions.ClientException: Parameter provided for node creation is not a Map
 at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage (SocketResponseHandler.java:68)
    org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage (PackStreamMessageFormatV1.java:456)
    org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read (PackStreamMessageFormatV1.java:417)
    org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne (SocketClient.java:130)
    org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne (SocketConnection.java:135)
    org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne (ConcurrencyGuardingConnection.java:150)
    org.neo4j.driver.internal.pool.PooledConnection.receiveOne (PooledConnection.java:170)
    org.neo4j.driver.internal.InternalStatementResult.tryFetchNext (InternalStatementResult.java:303)
    org.neo4j.driver.internal.InternalStatementResult.hasNext (InternalStatementResult.java:181)
```

If you were to replace the internal map with a `java.util.HashMap` and now a clojure map it all works. Need to investigate this as well.

**Comment by michaelklishin** [comment]
Libraries can do normalization but that assumes that keys are always strings or string-like things (e.g. keywords) and not arbitrary objects. If the latter is the case, it becomes a library user's responsibility.

**Comment by tuddman** [comment]
neo only supports 1-level deep properties, so no deeply nested data anyway.
And all the properties (keys) have to be a string... they can't be arbitrary objects.
Even arrays have to be all of the same primitive type (String | Number | Boolean ...), lest you get:
```
Collections containing mixed types can not be stored in properties.
```

so could it be the responsibility of this library to do something like:

```
(flatten (stringify-keys data))
```
 would need to investigate more to see where / how that would play into handing to a  `java.util.HashMap` in the [underlying driver](http://neo4j.com/docs/api/java-driver/current/index.html)

**Comment by michaelklishin** [comment]
Then this case is very similar to e.g. what happens in Monger and in some extent, Elastisch.

**Comment by ducky427** [comment]
I've tracked down the issue regarding maps and posted it on [neo4j-java-driver issue tracker](https://github.com/neo4j/neo4j-java-driver/issues/208)

**Comment by tuddman** [comment]
basic bolt protocol support is included & has been tested and is known working.

closing this issue.

Thanks @ducky427 !
